# Generated by Django 4.2 on 2024-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
