# Generated by Django 4.2 on 2024-09-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_word_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='by_cnt',
            field=models.IntegerField(default=10, verbose_name='何回テストで消す？'),
        ),
    ]
