# Generated by Django 4.2 on 2024-10-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_word_by_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rdmflag',
            field=models.BooleanField(default=False),
        ),
    ]
