services:
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    container_name: app_container
    # links:
    #   - db 
    privileged: true
    volumes:
      - .:/app
    environment:
        TZ: Asia/Tokyo
    # entrypoint: "sh build.sh"

  # db:
  #   # platform: linux/x86_64a // この行を追加。
  #   platform: linux/amd64
  #   container_name: db_container
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: memo
  #     MYSQL_USER: hoge
  #     MYSQL_PASSWORD: fuga
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #     - ./db/data:/var/lib/mysql
  #     - ./db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 3306:3306